{% set name = "neuraxle" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ece9e7b833037554f222d6360cb4317230f6957e042bb2383445a892e7b7ac11

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pytest
  source_files:
    - testing
  commands:
    - pytest testing

about:
  home: https://www.neuraxle.org/stable/index.html
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A Sklearn-like Framework for Hyperparameter Tuning in Deep Learning projects. Finally have the right abstractions and design patterns to properly do AutoML. Let your pipeline steps have hyperparameter spaces. Enable checkpoints to cut duplicate calculations. Go from research to production environment easily.'

  description: 'A Sklearn-like Framework for Hyperparameter Tuning in Deep Learning projects. Finally have the right abstractions and design patterns to properly do AutoML. Let your pipeline steps have hyperparameter spaces. Enable checkpoints to cut duplicate calculations. Go from research to production environment easily.'
  doc_url: https://www.neuraxle.org/stable/index.html
  dev_url: https://github.com/Neuraxio/Neuraxle

extra:
  recipe-maintainers:
    - guillaume-chevalier
